services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/var/www/html
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./backend/public:/var/www/html/public:ro
    - ./backend/storage/app/public:/var/www/html/storage/app/public:ro
    depends_on:
      - api

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: backend
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin:5.1-apache
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  dbdata:
